### PR TITLE
Initial idea for a rake task

### LINKED ISSUE #21: Add Rake task for Beaker rspec
Similar to the rspec-system one: https://github.com/puppetlabs/rspec-system/blob/master/lib/rspec-system/rake_task.rb

### PR DESCRIPTION
**Pull request by petems**
Fixes #21

Basic idea for now, any suggestions on default options and the like?

### CODE REVIEW

**Comment by anodelman** [comment]
Is this still wanted?  (Sorry for the long delay!)

**Comment by igalic** [comment]
good question, i think most projects fix it up themselves somehow.
see for instance [puppet-module-skeleton](https://github.com/garethr/puppet-module-skeleton/blob/master/skeleton/Rakefile#L32-L35)

**Comment by jlambert121** [comment]
Having a rake task removes a few more lines of boilerplate in each Rakefile - I'd still say it's useful.

**Comment by igalic** [comment]
merge away then…!

**Comment by petems** [comment]
I'm still up for a merge! :+1:

**Pull request merged**
