### PR TITLE
(BKR-345) Cleanup and quit on ctrl-c

### PR DESCRIPTION
**Pull request by electrical**

### CODE REVIEW

**Comment by electrical** [comment]
@anodelman @kevpl @DavidS  very simple change but works as requested.

**Comment by anodelman** [comment]
@electrical thanks for this.  I'll look it over and see if it covers what we are looking for.

**Comment by electrical** [comment]
did anyone review if this is the feature we wanted?

**Comment by kevpl** [comment]
@electrical I apologize, but we did not.  I'll take a look at this, and get back to you by the end of the week on it.

**Comment by electrical** [comment]
@kevpl cool np. i know how busy you guys are :-)

**Comment by kevpl** [comment]
right at the :checkered_flag: !  Checked it out, and tested locally, looks good.  Will kick off testing now, and merge when it passes automation

**Comment by kevpl** [comment]
@puppetlabs-jenkins test this please

**Comment by electrical** [comment]
Yay \o/

**Pull request merged**
