### PR TITLE
(BKR-474) Add missing shellescape

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by DavidS** [comment]
I've got a acceptance test that is failing on the original error, and this patch only changes the error I get.

Using the original line from before a6b3e50 works for me.

**Comment by rick** [comment]
@DavidS is the acceptance test linkable?

**Comment by DavidS** [comment]
It's the puppetlabs-apache acceptance test suite, which uses serverspec and therefore hits this.

**Comment by rick** [comment]
From @DavidS -- here's the build output from that run, with various failures caused by this problem:

  https://jenkins-modules.puppetlabs.com/job/forge-module_puppetlabs-apache_intn-sys_smoke-master/PLATFORM=ubuntu-1404-64mda,WORKER_LABEL=beaker/3/console

and the suite in question: https://github.com/puppetlabs/puppetlabs-apache/tree/00b0da75cbe2a11a8577b87cb635d0c04440db10/spec/acceptance

It seems like we should supplement our in-tool acceptance testing (probably we can use that suite above as a guide) here, since we know our suite isn't detecting the problem...

**Comment by justinstoller** [comment]
@rick @DavidS I believe this QENG-2889

**Comment by rick** [comment]
> @rick @DavidS I believe this QENG-2889

Meaning, this is what's causing QENG-2889?

**Comment by justinstoller** [comment]
Yeah, sorry. In complete sentences this time.

I'm in a meeting with @DavidS and from our discussion, I thought this was possibly the root cause of QENG-2889. On further review of the apache logs and comparing them to failures for concat, inifile, & ntp, I think this is a similar (failing when sending a command with a space in it) but different issue with QENG-2889 only affecting Solaris.

Sorry, for the noise.

**Comment by DavidS** [comment]
Since the jankins-modules is not public, here the relevant log snippet:
```
    File "/etc/apache2/apache2.conf"

pxs25p4f40hrvzw.delivery.puppetlabs.net (ubuntu-1404-agent) 11:27:29$ /bin/sh -c "test -f /etc/apache2/apache2.conf"

pxs25p4f40hrvzw.delivery.puppetlabs.net (ubuntu-1404-agent) executed in 0.01 seconds
      should be file

pxs25p4f40hrvzw.delivery.puppetlabs.net (ubuntu-1404-agent) 11:27:29$ /bin/sh -c "grep -qs -- ServerRoot\ \"/tmp/root\" /etc/apache2/apache2.conf || grep -qFs -- ServerRoot\ \"/tmp/root\" /etc/apache2/apache2.conf"

pxs25p4f40hrvzw.delivery.puppetlabs.net (ubuntu-1404-agent) executed in 0.01 seconds
Exited: 1
      should contain "ServerRoot \"/tmp/root\"" (FAILED - 1)
```

compare this to the last good run:

https://jenkins-modules.puppetlabs.com/job/forge-module_puppetlabs-apache_intn-sys_smoke-master/PLATFORM=ubuntu-1404-64mda,WORKER_LABEL=beaker/1/consoleFull
```
    File "/etc/apache2/apache2.conf"

n8m7f3oqnwn5ceh.delivery.puppetlabs.net (ubuntu-1404-agent) 11:36:51$ /bin/sh -c test\ -f\ /etc/apache2/apache2.conf

n8m7f3oqnwn5ceh.delivery.puppetlabs.net (ubuntu-1404-agent) executed in 0.01 seconds
      should be file

n8m7f3oqnwn5ceh.delivery.puppetlabs.net (ubuntu-1404-agent) 11:36:51$ /bin/sh -c grep\ -qs\ --\ ServerRoot\\\ \\\"/tmp/root\\\"\ /etc/apache2/apache2.conf\ \|\|\ grep\ -qFs\ --\ ServerRoot\\\ \\\"/tmp/root\\\"\ /etc/apache2/apache2.conf

n8m7f3oqnwn5ceh.delivery.puppetlabs.net (ubuntu-1404-agent) executed in 0.01 seconds
      should contain "ServerRoot \"/tmp/root\""
```

**Comment by electrical** [comment]
For some reason i'm getting the following error when implementing this fix:

```
  28) elasticsearch class: module removal Service "elasticsearch-es-02" should not be running
      Failure/Error: it { should_not be_running }
      TypeError:
        can't convert Symbol into Integer

      # ./.vendor/ruby/1.9.1/gems/specinfra-2.43.0/lib/specinfra/command_factory.rb:26:in `[]'
      # ./.vendor/ruby/1.9.1/gems/specinfra-2.43.0/lib/specinfra/command_factory.rb:26:in `create_command_class'
      # ./.vendor/ruby/1.9.1/gems/specinfra-2.43.0/lib/specinfra/command_factory.rb:16:in `get'
      # ./.vendor/ruby/1.9.1/gems/specinfra-2.43.0/lib/specinfra/processor.rb:4:in `check_service_is_running'
      # ./.vendor/ruby/1.9.1/bundler/gems/beaker-rspec-49c45f6102fe/lib/beaker-rspec/helpers/serverspec.rb:132:in `method_missing'
      # ./.vendor/ruby/1.9.1/gems/serverspec-2.23.0/lib/serverspec/type/service.rb:24:in `running?'
      # ./.vendor/ruby/1.9.1/gems/serverspec-2.23.0/lib/serverspec/matcher/be_running.rb:4:in `block (2 levels) in <top (required)>'
      # ./spec/acceptance/002_class_spec.rb:144:in `block (4 levels) in <top (required)>'
```

Any idea's ?

**Comment by DavidS** [comment]
@electrical Yeah that is the error I was referring to in https://github.com/puppetlabs/beaker-rspec/pull/74#issuecomment-137079395 - reverting the line to what was there before works for Linux, but fails on Windows, so it's not the whole solution.

**Comment by mcanevet** [comment]
Fixed by https://github.com/puppetlabs/beaker-rspec/pull/75

**Pull request closed without merging**
