### PR TITLE
Add Dependabot to keep thins up to date

### PR DESCRIPTION
**Pull request by genebean**

### CODE REVIEW

**Comment by genebean** [comment]
Jenkins restest this please

**Comment by shaigy** [comment]
Looks like the pe_dir path is not correctly set in the job. It is picking up the default path from beaker_pe and is failing
```[31m  		No such file or directory @ rb_sysopen - /opt/enterprise/dists/LATEST[0m```

**Comment by genebean** [comment]
@shaigy do you know how we fix that error?

**Review by heathseals — APPROVED** [review]

**Review by trvs-sdlr — APPROVED** [review]
The changes here look sufficient to me

**Pull request merged**
