### PR TITLE
(BKR-968) README improvements

### PR DESCRIPTION
**Pull request by kevpl**
ping @wyardley, @beergeek for your involvement in #85. Is there anything I'm missing from your concerns?

### CODE REVIEW

**Comment by wyardley** [comment]
I think @beergeek didn't get tagged, so tagging.
Looks good to me...
For the puppet 4 example, maybe I'm missing something, but should the example give an example of what 'options' should be here?

` +install_puppet_agent_on(hosts, options)`

**Comment by beergeek** [comment]
Looks good to me too :-)

**Comment by kevpl** [comment]
actually, [`options` is a method call in the beaker-rspec shim](https://github.com/puppetlabs/beaker-rspec/blob/master/lib/beaker-rspec/beaker_shim.rb#L26-L28) that grabs beaker's global options hash. It's not representing a variable or anything that a user would need to replace, they can use the method as-is.

**Comment by ferglor** [comment]
👍

**Pull request merged**
