### PR TITLE
(BKR-1049) Updating require to align with oldest supported PE version. This also matches the merged beaker PR.

### PR DESCRIPTION
**Pull request by cdenneen**

### CODE REVIEW

**Comment by cdenneen** [comment]
Failed based on bad travis config it seems... not the change

**Comment by trevor-vaughan** [comment]
@cdenneen I have a PR coming your way to touch some of this up

**Comment by cdenneen** [comment]
@trevor-vaughan thanks... re-running test now

**Comment by trevor-vaughan** [comment]
@cdenneen No problem. I *really* need this gem so that I can get rid of all my hacky workarounds for the non-PE compatible Beaker.

**Comment by trevor-vaughan** [comment]
Huh..it didn't seem to pick up the travis.yml

**Comment by cdenneen** [comment]
@trevor-vaughan no Rakefile

**Comment by trevor-vaughan** [comment]
@cdenneen That shouldn't matter, I'm not running Rake. I'm just building the gem. There aren't any spec tests.

**Comment by cdenneen** [comment]
@trevor-vaughan Yeah I know I was just reading the error... now it appears rubygems.org is having issues... this build will never pass lol

**Comment by trevor-vaughan** [comment]
(╯°□°)╯  ┻━┻

**Comment by cdenneen** [comment]
@trevor-vaughan I added a 2.1 rvm test since this is to port to support oldest PE supported version.
(don't think 1.9.x is officially supported anymore)... regardless that seems to cause a new error:

```
Gem::InstallError: rack requires Ruby version >= 2.2.2.
```

**Comment by trevor-vaughan** [comment]
@cdenneen I would just ditch 1.9. I pulled the travis.yml from the main beaker project.

**Comment by trevor-vaughan** [comment]
Ugh, Rubygems.org died again :disappointed:

**Comment by cdenneen** [comment]
@trevor-vaughan where is rack specified... need to force that version I think to 1.6.5 in order for 2.1 to pass

**Comment by trevor-vaughan** [comment]
@cdenneen Are you sure? The error was `503 Service Unavailable`

**Comment by cdenneen** [comment]
@trevor-vaughan yes Gem::InstallError: rack requires Ruby version >= 2.2.2. the 503 is retryable it seems... but this isn't... so need to force rack below < 2.0.1 when 2.1 of ruby

**Comment by trevor-vaughan** [comment]
@cdenneen Weird. I've just set my RVM to 2.1.9 and running `bundle install` picks up `rack 1.6.5` without needing to do anything at all.

**Comment by cdenneen** [comment]
@trevor-vaughan in travis it doesn't seem that way ;)

**Comment by trevor-vaughan** [comment]
@cdenneen I guess you'll just have to add the dep to the Gemfile then and call it done.

**Comment by cdenneen** [comment]
@trevor-vaughan gemspec or Gemfile? If you wouldn't mind sending another PR might make it quicker (also set my fork up to build with PR so will know if it works before I merge it)

**Comment by cdenneen** [comment]
Can someone clear the cache on this and restart the build. My upstream built fine but this is still caching 2.1 vs 2.1.9

**Comment by cdenneen** [comment]
@puppetlabs-jenkins please test

**Comment by cdenneen** [comment]
@trevor-vaughan thanks everything is good now. I've squashed the PR so all should be good now.
@tvpartytonight if this can be merged now. cc @kevpl

**Pull request merged**
